# Day 31 — "Singular Value Decomposition (SVD): The Geometry of Any Linear Transformation"

Every linear map is a rotate → stretch → rotate operation. SVD makes that geometry explicit.


In [3]:
# Ensure repo root is on sys.path for local imports
import sys
from pathlib import Path

repo_root = Path.cwd()
if not (repo_root / "days").exists():
    for parent in Path.cwd().resolve().parents:
        if (parent / "days").exists():
            repo_root = parent
            break

sys.path.insert(0, str(repo_root))
print(f"Using repo root: {repo_root}")


Using repo root: /media/abdul-aziz/sdb7/masters_research/math_course_dlcv


## 1. Core Intuition

A unit circle pushed through any matrix becomes an ellipse. SVD explains this as:

- rotate into special input axes
- stretch by singular values
- rotate into output space


## 2. SVD Decomposition

A = U * Sigma * V^T

- V^T rotates input space
- Sigma stretches along orthogonal axes
- U rotates output space


## 3. Singular Values

Large singular values amplify directions. Small values suppress them. Zero values destroy information.


## 4. Rank, Null Space, Compression

Rank equals the number of non-zero singular values. Low-rank structure explains compression and denoising.


## 5. Python — SVD Summary

`days/day31/code/svd_demo.py` prints U, singular values, and V^T.


In [4]:
import numpy as np
from days.day31.code.svd_demo import svd_summary, low_rank_approx

A = np.array([[3, 1], [1, 3], [0, 2]], dtype=float)
svd_summary(A)
print("Low-rank (k=1):", low_rank_approx(A, k=1))


U:
 [[-0.59928555  0.77614129  0.19611614]
 [-0.7051238  -0.39578604 -0.58834841]
 [-0.37902146 -0.49087485  0.78446454]]
Singular values:
 [4.28071902 2.38231918]
Vt:
 [[-0.58471028 -0.81124219]
 [ 0.81124219 -0.58471028]]
Low-rank (k=1): [[1.5        2.08113883]
 [1.76491106 2.4486833 ]
 [0.9486833  1.31622777]]


## 6. Visualization — Circle to Ellipse

`days/day31/code/visualizations.py` plots a unit circle and its transformed ellipse.


In [5]:
from days.day31.code.visualizations import plot_circle_ellipse, plot_singular_values

RUN_FIGURES = False

if RUN_FIGURES:
    plot_circle_ellipse()
    plot_singular_values()
else:
    print("Set RUN_FIGURES = True to regenerate Day 31 figures inside days/day31/outputs/.")


Set RUN_FIGURES = True to regenerate Day 31 figures inside days/day31/outputs/.


## 7. Why SVD Matters in Deep Learning

- PCA and low-rank compression depend on singular values.
- Singular spectra show which directions matter in embeddings.
- Exploding singular values destabilize training.


## 8. Mini Exercises

1. Compute SVD of random weights and plot singular values.
2. Zero out small singular values and reconstruct the matrix.
3. Compare spectra for trained vs untrained layers.


## 9. Key Takeaways

- Every matrix = rotate → stretch → rotate.
- Singular values measure importance of directions.
- Rank tells you the effective dimensionality.
- SVD explains compression, denoising, and embedding geometry.
